spring:
  application:
    name: familyMeet
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8000

setTime:
  refreshToken: 30
  accessToken: 300

jwt:
  secret: ${JWT_SECRET}
