spring:
  application:
    name: familyMeet
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8000

setTime:
  refreshToken: 30 # minutes
  accessToken: 300 # minutes

jwt:
  secret: ${JWT_SECRET}
redis:
  stream:
    key: chat-stream
    group: chat-group
    consumer: chat-consumer-${random.uuid}
    dlq: chat-stream-dlq
